package lab11_05_06.parser;

public enum TokenType { // important: SKIP, IDENT, NUM, STRING,  must have ordinals 1 2 3 4
	EOF, SKIP, IDENT, NUM, STRING, PRINT, LET, PLUS, TIMES, EQ, ASSIGN, OPEN_PAR,
	CLOSE_PAR, OPEN_PAIR, CLOSE_PAIR, STMT_SEP, EXP_SEP, OPEN_BLOCK, CLOSE_BLOCK, MINUS, NOT, AND, BOOL,
	IF, ELSE, FST, SND,  
}
